name: Hackage Index CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  "Job":
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'macOS-latest'
          - 'ubuntu-latest'
          - 'windows-latest'

        ghc:
          - '8.10.2'
          - '8.8.4'
          - '8.6.5'
    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'
        enable-stack: true

    - name: 'Setup'
      shell: bash
      run: |
        cabal --version
        ghc --version
        cabal user-config update -a "http-transport: plain-http" -v3
        cabal user-config diff


    - run: cabal v2-update
    - run: cabal v2-freeze $CONFIG

    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build dependencies
      run: cabal v2-build --only-dependencies $CONFIG
    - name: Build
      run: cabal v2-build $CONFIG
    - name: Test
      run: cabal v2-test $CONFIG
    - name: Haddock
      run: cabal v2-haddock $CONFIG --haddock-executables

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ludeeus/action-shellcheck@master
      with:
        ignore: tests
